import glob
import os.path

# import variables from other scons files
Import( '*' )



if have_flycapture2:
	env = masterEnv.Clone()
	# take driver name from directory name, replace if you don't like the result
	driverName = "flycapture2multi"

	# automatically glob files
	headers = []
	sources = 'OpenNI2FrameGrabber.cpp'

	# append driver specific build options here
	env.AppendUnique( **utvision_all_options )
	env.AppendUnique( **utdataflow_all_options )	
	env.AppendUnique( **flycapture2_options )

	# compile driver
	setupSingleComponentBuild(env, sources, driverName,'flycapture2multi')

	# also create a visual studio project for the driver
	createVisualStudioProject(env, sources, headers, driverName)
